apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pgsql
  namespace: keycloak
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cephfs-sc-ephemeral