## Create a PostgreSQL cluster using the CloudNative-PG operator
## (https://github.com/cloudnative-pg/cloudnative-pg)
##
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-cnpg
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.keycloakx.database.replicas }}
  bootstrap:
    initdb:
      database: {{ .Values.keycloakx.database.database }}
      owner: {{ .Values.keycloakx.database.username }}
      secret:
        name: {{ .Values.keycloakx.database.existingSecret }}
      encoding: UTF8
      localeProvider: icu
      icuLocale: en_US
      localeCType: en_US.UTF-8
      localeCollate: en_US.UTF-8
  storage:
    storageClass: {{ .Values.keycloakx.database.storageClass }}
    size: {{ .Values.keycloakx.database.size }}
  backup:
    volumeSnapshot:
      className: csi-cephfsplugin-snapclass

